project:
  output-dir: ./docs/ca

lang: ca

website:
  navbar:
    right:
      - icon: github
        href: https://github.com/neurodevco
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/neurodevco
        aria-label: Twitter
    left:
      - href: people.qmd
        text: Qui som?
      - text: Recerca
        menu:
          - text: Estudis amb beb√®s
            href: babies.qmd
          - text: Estudis amb animals
            href: animals.qmd
      - href: contact.qmd
        text: Contacte
